# **Dataset Preparation & Preprocessing**

## Load Data

In [1]:
# đọc dữ liệu
import pandas as pd
data = pd.read_csv('Resources\glass.data', header = None)
# value = data.loc[:,data.columns != 0]
# value = value.select_dtypes(include=["float64", "int64"])
# label = data.loc[:, data.columns ==0]
# label
data

0        1      2     3     4      5     6     7     8    9   10
0      1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0   1
1      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0   1
2      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0   1
3      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0   1
4      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0   1
..   ...      ...    ...   ...   ...    ...   ...   ...   ...  ...  ..
209  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0   7
210  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0   7
211  212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0   7
212  213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0   7
213  214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0   7

[214 rows x 11 columns]

In [1]:
import numpy as np
x = np.zeros(1)
x

array([0.])

In [3]:
data

0        1      2     3     4      5     6     7     8    9   10
0      1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0   1
1      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0   1
2      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0   1
3      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0   1
4      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0   1
..   ...      ...    ...   ...   ...    ...   ...   ...   ...  ...  ..
209  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0   7
210  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0   7
211  212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0   7
212  213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0   7
213  214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0   7

[214 rows x 11 columns]

In [20]:
import numpy as np
value = data.loc[:,data.columns != 10]
value = value.loc[:,value.columns >=1]
value
value = value.select_dtypes(include=["float64", "int64"])
# label = data.loc[:, data.columns == col_label]
label = data.loc[:,data.columns == 10]


label_list = pd.unique(label[label.columns[0]])
label_list = label_list.tolist()
label_count = np.array(label[label.columns[0]].value_counts())
label_count
# label_list
# label
# label.columns[0]
final_data = value
# final_data[''] = label
# final_data_table = np.array(final_data)
# final_data_table.tolist()

KeyError: ''

In [2]:
value = data.loc[:,data.columns != 10]
value = value.loc[1:,value.columns >=1]
label = data.loc[:,data.columns == 10]
value['']=label
value
value.reset_index()
value.columns = range(value.shape[1])
value

0      1     2     3      4     5     6     7     8  9
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.00  1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.00  1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.00  1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.00  1
5    1.51596  12.79  3.61  1.62  72.97  0.64  8.07  0.00  0.26  1
..       ...    ...   ...   ...    ...   ...   ...   ...   ... ..
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.00  7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.00  7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.00  7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.00  7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.00  7

[213 rows x 10 columns]

In [4]:
# Xử lý nhãn dư, đếm nhãn
import numpy as np
label_list = pd.unique(label[label.columns[0]])
label_list = label_list.tolist()
num_class = len(label_list)
label_data =label[label.columns[0]].values.tolist()
label_count = np.array(label[label.columns[0]].value_counts())


1

In [29]:
print(label_list)

[1, 2, 3, 5, 6, 7]


In [30]:
import numpy as np
X = np.array(value)
n = X.shape[0]
p = X.shape[1]
print(X.shape)
X

(213, 10)


array([[ 1.51761, 13.89   ,  3.6    , ...,  0.     ,  0.     ,  1.     ],
       [ 1.51618, 13.53   ,  3.55   , ...,  0.     ,  0.     ,  1.     ],
       [ 1.51766, 13.21   ,  3.69   , ...,  0.     ,  0.     ,  1.     ],
       ...,
       [ 1.52065, 14.36   ,  0.     , ...,  1.64   ,  0.     ,  7.     ],
       [ 1.51651, 14.38   ,  0.     , ...,  1.57   ,  0.     ,  7.     ],
       [ 1.51711, 14.23   ,  0.     , ...,  1.67   ,  0.     ,  7.     ]])

## Generate U_ngang , V

In [38]:
dict_cluster = {}

In [39]:
len(dict_cluster)

0

In [40]:
c = 0
def set_c(input):
    global c
    c = input

In [41]:
from random import random
import random

def generate_U_ngang(k1):
    global U_ngang
    global index_x_giamsat
    global sum_i
    U_ngang = np.zeros((n,c))
    
    
    index_x_giamsat = random.sample(range(n),k1)# CHọn k1 vector x từ n vector x ban đầu  
    index_x_giamsat = np.sort(index_x_giamsat)

    for i in range(k1):
        if len(dict_cluster) == 0 :
            c1= random.randint(0,c-1)
        else:
            c1= dict_cluster[label_data[index_x_giamsat[i]]]
            #Chọn vị trí cụm giám sát
        U_ngang[index_x_giamsat[i]][c1] = 0.5     
    sum_i= sum(U_ngang.T)
# #Maxtrix U_ngang
# for i in range(n):
#     print(str(i) +" : "+ str(U_ngang[i]))

In [17]:
import random
import numpy as np
a = np.zeros((3,2))
index_x_giamsat = random.sample(range(5),2)
index_x_giamsat = np.sort(index_x_giamsat)
index_x_giamsat
for i in range(5):
    print(i)
c1 = random.randint(0,3)
type(c1)
pow(2,3)
a = [2,3,5]
a= np.array(a)
b = [1,6,7]
b = np.array(b)
k = sum(pow(a-b,2))

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# arr[0] = a[0]/sum(a[0])
sum(arr[0])


0
1
2
3
4


6

In [34]:
#Maxtrix V sinh ngau nhien

def generate_V():
    global V
    V = np.random.rand(c,p) 

## Function 4 ,6

In [35]:
# Tinh d_ki (trong cong thuc 6)
def d_ki(k, i):
    kq = sum(  pow(X[k] - V[i], 2) )
    return kq     

In [36]:
#Cong thuc so 6



def cong_thuc_6(m):
    Z = np.zeros((n,c))
    #tu day suy ra U = U_ngang + Z ta tinh Z

    D = np.zeros((n,c))
    for k in range(n):
        for i in range(c):
            D[k][i] = pow(d_ki(k,i),1/(1-m))    
        D[k] = D[k]/sum(D[k])    
      
    #Z = (1/d_ki)^1/m-1z = np.array (i = 1 ,c)
    for i in range(n) :
        Z[i] = (1 - sum_i[i] )*D[i]
        
    return U_ngang+Z  # tuc la U  

In [37]:
def cong_thuc_4(m):
    V_temp = np.zeros((c,p))
    U_temp = abs(U - U_ngang)
    U_temp = pow(U_temp,m)
    for i in range(c):
        tu_so = np.zeros(p)
        for k in range(n):
           tu_so +=U_temp[k][i] * X[k] 
        V_temp[i] = tu_so/ sum((U_temp.T)[i])
    return V_temp

# **Đánh giá kết quả**

In [38]:
# đếm số lượng phần tử mỗi cụm tương ứng với từng lớp nhãn dữ liệu
def count_class(num_class, num_cluster):
    global count_class_cluster
    count_class_cluster = np.zeros((num_class,num_cluster), dtype="int64")
    for k in range(n):
        k_class = label_list.index(label_data[k]) #Lấy ra vị trí của nhãn trong label_list của phần tử thứ k trong dataset
        index_max = np.argmax(U[k]) #Lấy ra chỉ số của giá trị độ thuộc lớn nhất của phần tử thứ k
        count_class_cluster[k_class][index_max] +=1   
    # Ma trận có num_class dòng và num_cluster cột, phần tử thứ i,j của ma trận thuộc class i, cluster j
     

In [9]:
label_list = [1,2,3,5,6,7]
k_class = label_list.index(label_data[71])
np.argmax(np.array(label_list))

5

In [39]:

# Các độ đo
def external_validity(num_class, c):
    a1 = b1 = c1 = d1= 0
    for i in range(num_class):
        a1+= sum ( (count_class_cluster[i]-1)*count_class_cluster[i]/2 )
        b1+= (pow(sum(count_class_cluster[i]),2) - sum(pow(count_class_cluster[i],2)) )/2
    for i in range(num_class-1):
        for j in range(i+1, num_class):
            for k in range(c):
                c1+=count_class_cluster[i][k] * count_class_cluster[j][k]
                for h in range(c):
                    if h!=k :
                        d1+=count_class_cluster[i][k] * count_class_cluster[j][h]  
    print("a1= "+str(a1))
    print("b1= "+str(b1))
    print("c1= "+str(c1))
    print("d1= "+str(d1))
    # Rand int
    w1 =  (a1 + d1)/ (a1 +b1 + c1 +d1)
    # Adjusted Rand Index
    M= a1 + b1 +c1 +d1
    w2 = (a1 - (a1+c1)*(a1+b1)/M) /( (2*a1+b1+c1)/2 - (a1+c1)*(a1+b1)/M )
    #Jaccard Coefficient
    w3 = a1 / (a1+b1+c1)
    print ("Rand Index :" +str(w1))
    print ("Adjusted Rand Index :" + str(w2))
    print ("Jaccard Coefficient" +str(w3))
    

In [40]:
def Meam_accuraccy():
    sum_cluster = sum(count_class_cluster)
    mean_accuraccy = sum_cluster/label_count
    print(np.amin(mean_accuraccy))
        
    
    

In [41]:
def set_dict_cluster():
    global dict_cluster
    for i in range(num_class):
        temp = np.argmax(count_class_cluster[i])
        dict_cluster[label_list[i]] = temp
    return

def rs_dict_cluster():
    global dict_cluster
    dict_cluster = {}
    return

# **Thuật toán**

In [42]:
def thuat_toan_1_pha(epsilon,m,c,k1):
    global U,V,count_class_cluster
    global dict_cluster
    dict_cluster = {}
    
    set_c(c)
    generate_U_ngang(k1)
    generate_V()

    Epsilon = np.zeros((c,p)) + epsilon
    i=1
    while True:
        # print("-----------------------\nChay lan "+ str(i)+"\n")
        i+=1
        U= cong_thuc_6(m)
        V_truoc =V
        V= cong_thuc_4(m)
        delta_V = abs(V- V_truoc)
        ktra = np.less_equal(delta_V, Epsilon)
        if (np.all(ktra)):
            break
    print("\n------------------------------------\nKetqua\nV:")
    print(V)
    count_class(num_class, c)
    external_validity(num_class, c)
    # Meam_accuraccy()
    return

In [43]:
def thuat_toan_2_pha(epsilon,m,c,k1):
    global V,U, count_class_cluster, dict_cluster
    set_c(c)
    generate_V()
    V_temp = V
    # Pha 1 (Khong giam sat k1 = 0)
    dict_cluster = {}
    generate_U_ngang(0) 
    Epsilon = np.zeros((c,p)) + epsilon
    while True:
        U= cong_thuc_6(m)
        V_truoc = V
        V= cong_thuc_4(m)
        delta_V = abs(V- V_truoc)
        ktra = np.less_equal(delta_V, Epsilon)
        if (np.all(ktra)):
            break
    count_class(num_class, c)
    set_dict_cluster()  
    #Pha 2(Co giam sat k1 = k1)
    generate_U_ngang(k1)
    while True:
        U= cong_thuc_6(m)
        
        V_truoc = V
        V= cong_thuc_4(m)
        
        delta_V = abs(V- V_truoc)
        ktra = np.less_equal(delta_V, Epsilon)
        if (np.all(ktra)):
            break
    print("\n------------------------------------\nKetqua\nV:")
    print(V)
    count_class(num_class, c)
    external_validity(num_class, c)
    # Meam_accuraccy()
    rs_dict_cluster()
    return
    
    
    

# **Main**

In [44]:
thuat_toan_2_pha(1e-6,2,4,150)


------------------------------------
Ketqua
V:
[[1.51708835e+00 1.43619615e+01 3.40097819e-01 2.15929584e+00
  7.31493835e+01 1.92971374e-01 8.72508359e+00 9.95055143e-01
  1.85087577e-02 6.79335687e+00]
 [1.51818038e+00 1.31313070e+01 3.41693483e+00 1.27295299e+00
  7.26960750e+01 5.29734224e-01 8.73539926e+00 2.12162556e-02
  7.17499455e-02 1.25367722e+00]
 [1.51746138e+00 1.32296308e+01 3.45154496e+00 1.41108941e+00
  7.26276794e+01 5.59263161e-01 8.46253054e+00 2.85088591e-02
  5.98050851e-02 2.21912421e+00]
 [1.52599741e+00 1.26351171e+01 2.69344949e-01 1.40311423e+00
  7.16288040e+01 4.14055336e-01 1.31335774e+01 2.85082167e-01
  1.52010866e-01 2.39147445e+00]]
a1= 5314.0
b1= 579.0
c1= 1569
d1= 15116
Rand Index :0.9048631411108158
Adjusted Rand Index :0.7660891928264941
Jaccard Coefficient0.7121415170195659


In [45]:
thuat_toan_2_pha(1e-6,2, 4, 150)


------------------------------------
Ketqua
V:
[[1.51718598e+00 1.31587524e+01 3.50736322e+00 1.41246739e+00
  7.28131506e+01 5.64374472e-01 8.30993140e+00 1.89888458e-02
  5.43185208e-02 1.93513499e+00]
 [1.51680470e+00 1.44363383e+01 3.56137749e-01 2.25206910e+00
  7.30315674e+01 1.68768988e-01 8.84472661e+00 8.35547625e-01
  2.43408800e-02 6.80639183e+00]
 [1.51974407e+00 1.35330154e+01 3.49418762e+00 1.12745894e+00
  7.21910807e+01 3.83855895e-01 9.05626507e+00 5.60438926e-02
  6.06299065e-02 1.41174779e+00]
 [1.52252909e+00 1.35249323e+01 7.65968297e-01 1.33716142e+00
  7.21781804e+01 3.38070870e-01 1.15419429e+01 1.10708177e-01
  7.86832294e-02 3.05204978e+00]]
a1= 4809.0
b1= 1084.0
c1= 2439
d1= 14246
Rand Index :0.8439631499689964
Adjusted Rand Index :0.6235086551936203
Jaccard Coefficient0.5771723475756121


In [46]:
U

array([[2.67930859e-01, 9.46013740e-03, 7.05741136e-01, 1.68678670e-02],
       [6.22513711e-01, 1.81789065e-02, 3.27382790e-01, 3.19245928e-02],
       [2.71734237e-01, 5.45946305e-03, 7.11802981e-01, 1.10033188e-02],
       [3.16840123e-01, 6.97849657e-03, 6.62919309e-01, 1.32620716e-02],
       [3.29171073e-01, 8.02656161e-03, 6.47523612e-01, 1.52787537e-02],
       [3.04714145e-01, 6.82424083e-03, 6.75126400e-01, 1.33352145e-02],
       [6.10938189e-01, 1.51497918e-02, 3.43969090e-01, 2.99429285e-02],
       [3.21040229e-01, 1.49904371e-02, 6.33251829e-01, 3.07175056e-02],
       [3.03588420e-01, 6.01291296e-03, 6.77871240e-01, 1.25274269e-02],
       [3.30512417e-01, 9.12274192e-03, 6.42907236e-01, 1.74576048e-02],
       [2.87001688e-01, 6.71859453e-03, 6.91762450e-01, 1.45172674e-02],
       [3.31265709e-01, 8.92967745e-03, 6.42854103e-01, 1.69505108e-02],
       [3.11234247e-01, 7.46153288e-03, 6.65951897e-01, 1.53523230e-02],
       [3.03522647e-01, 8.96172511e-03, 6.68730743e

In [47]:
np.round(U, 4)

array([[2.679e-01, 9.500e-03, 7.057e-01, 1.690e-02],
       [6.225e-01, 1.820e-02, 3.274e-01, 3.190e-02],
       [2.717e-01, 5.500e-03, 7.118e-01, 1.100e-02],
       [3.168e-01, 7.000e-03, 6.629e-01, 1.330e-02],
       [3.292e-01, 8.000e-03, 6.475e-01, 1.530e-02],
       [3.047e-01, 6.800e-03, 6.751e-01, 1.330e-02],
       [6.109e-01, 1.510e-02, 3.440e-01, 2.990e-02],
       [3.210e-01, 1.500e-02, 6.333e-01, 3.070e-02],
       [3.036e-01, 6.000e-03, 6.779e-01, 1.250e-02],
       [3.305e-01, 9.100e-03, 6.429e-01, 1.750e-02],
       [2.870e-01, 6.700e-03, 6.918e-01, 1.450e-02],
       [3.313e-01, 8.900e-03, 6.429e-01, 1.700e-02],
       [3.112e-01, 7.500e-03, 6.660e-01, 1.540e-02],
       [3.035e-01, 9.000e-03, 6.687e-01, 1.880e-02],
       [6.212e-01, 1.560e-02, 3.310e-01, 3.220e-02],
       [2.735e-01, 7.900e-03, 7.010e-01, 1.760e-02],
       [2.196e-01, 2.440e-02, 6.966e-01, 5.940e-02],
       [7.920e-02, 4.300e-03, 9.064e-01, 1.020e-02],
       [5.702e-01, 1.200e-02, 3.922e-01, 2.550